version: "3.9"

services:
  rhgtgbot_app:
    build:
      context: ./bot
      dockerfile: Dockerfile
    container_name: rhgtgbot
    environment:
      BOT_TOKEN: 
      API_ID: 
      API_HASH: 
#      HTTP_PROXT: http://
#      HTTPS_PROXY: http://
      MONGO_DB_PORT: 
      MONGO_DB_HOST: 
      MONGO_DB_USER: 
      MONGO_DB_PASS: 
      TGBOT_HR_BOT_NAME: 
      TGBOT_OWNER_USERNAME: 
      TGBOT_DEFAULT_RIGHTS: 
    network_mode: "host"
#    netowrk_mode: "container:name"
    volumes:
      - ./bot_assets:/bot/assets
      - ./bot_logs:/bot/logs
    restart: never
  
    rhgtgbot_mongodb:
    image: mongo
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME:
      MONGO_INITDB_ROOT_PASSWORD:
    volumes:
      - ./db_data:/data/db
    deploy:
      resources:
        limits:
          cpus: 0.5
          memory: 512m
    restart: always