version: "3.9"

services:
  app:
    build:
      context: ./bot
      dockerfile: Dockerfile
    container_name: rhgtgbot
    environment:
      BOT_TOKEN: 
      API_ID: 
      API_HASH: 
#      HTTP_PROXT: http://
#      HTTPS_PROXY: http://
    network_mode: "host"
#    netowrk_mode: "container:name"
    volumes:
      - ./bot_assets:/bot/assets
      - ./bot_logs:/bot/logs
    restart: never
  
    db:
    image: mongo
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME:
      MONGO_INITDB_ROOT_PASSWORD:
    volumes:
      - ./db_data:/data/db
    ports:
      - "27017:27017"
    deploy:
      resources:
        limits:
          cpus: 0.5
          memory: 512m
    restart: always